name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install the package itself
      run: |
          echo requirements.txt
          pip install .

    - name: Install packages for testing
      run: |
        pip install -r requirements_dev.txt

    - name: Test with pytest
      run: |
        pytest --cov-report term --cov=reports

    - name: coveralls
      run: |
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
